### ISSUE TITLE
Error when initially connecting peers

### ISSUE THREAD

**Issue by smnz** [rust-bitcoin/rust-bitcoincore-rpc#108]
It is sometimes the case that when initially connecting to peers they report a startingheight of -1. Also, the pingtime field can occasionally be entirely absent. Here is an example peer that causes both problems. These usually resolve after a few seconds to minutes but in both cases there will be a JSON parse error and the entire get_peer_info() fails and becomes useless until they establish fully or are removed.

The pingtime field should be optional and the startingheight should be able to cope with a value of -1 (eg not u64).

```
  {
    "id": 15,
    "addr": "95.216.100.186:18333",
    "addrbind": "172.17.0.13:37250",
    "services": "0000000000000000",
    "servicesnames": [
    ],
    "relaytxes": false,
    "lastsend": 1590116798,
    "lastrecv": 0,
    "bytessent": 128,
    "bytesrecv": 0,
    "conntime": 1590116798,
    "timeoffset": 0,
    "version": 0,
    "subver": "",
    "inbound": false,
    "addnode": false,
    "startingheight": -1,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "permissions": [
    ],
    "minfeefilter": 0.00000000,
    "bytessent_per_msg": {
      "version": 128
    },
    "bytesrecv_per_msg": {
    }
  }
```

**Comment by stevenroose** [comment]
Thanks for the report. Fixed here: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/109
