### ISSUE TITLE
"blockheight" attribute in "listtransactions" / "gettransaction"

### ISSUE THREAD

**Issue by justinmoon** [rust-bitcoin/rust-bitcoincore-rpc#116]
[Bitcoin Core 20.0 added "blockheight" to listtransactions and gettransaction responses](https://github.com/bitcoin/bitcoin/issues/17296). Is this something rust-bitcoincore-rpc could support?

I was looking through the code a bit and didn't see any version-dependent deserialization which might be needed here ...

**Comment by stevenroose** [comment]
We do have some for getblockchaininfo IIRC. Because of the bip9 softforks that are encoded entirely differently.

But for simply extra fields, you can easily add them as optional fields.

**Comment by stevenroose** [comment]
Do you think this should be enough? https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/119

**Comment by justinmoon** [comment]
That works!
