### ISSUE TITLE
getaddressinfo's iswatchonly field

### ISSUE THREAD

**Issue by justinmoon** [rust-bitcoin/rust-bitcoincore-rpc#127]
This field is `Option` but it seems like it's never been optional: https://github.com/bitcoin/bitcoin/commit/b98bfc5ed0da1efef1eff552a7e1a7ce9caf130f#diff-df7d84ff2f53fcb2a0dc15a3a51e55ceR3691.

I'm not sure if it makes sense to change it since people are probably using this API.

Mostly making a note here in case someone in the future wonders what the option corresponds to.

**Comment by sgeisler** [comment]
I don't think that this crate and particular feature are so widely used that it would be problematic. I'd prefer a cleaner interface with less `expect/unwrap`s.
