### ISSUE TITLE
get_address_info incompatibility with Bitcoin Core v0.20.0

### ISSUE THREAD

**Issue by shesek** [rust-bitcoin/rust-bitcoincore-rpc#136]
- The `labels` field is now an array of label name strings. This can be restored to the previous object format with `name` and `purpose` using `-deprecatedrpc=labelspurpose` (expected to be removed entirely in v0.21).

- The `label` field was removed. It cannot be restored.

See: https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/getaddressinfo/

**Comment by stevenroose** [comment]
This was fixed in https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/139.
