### ISSUE TITLE
RBF Enabled

### ISSUE THREAD

**Issue by wchance** [rust-bitcoin/rust-bitcoincore-rpc#162]
When using getmempoolentry the bip-125-replaceable enabled field inherits from ancestors.    Wondering if this value has potential to change if ancestors are confirmed?    Also is there any other way to confirm if the transaction itself has RBF enabled or if it inherits from parents RBF Enabeld?

**Comment by sgeisler** [comment]
Good question, I think the value could change from taking a glance at the BIP (but please look it up in the bitcoin core code if you need a 100% answer). For confirming explicit RBF signaling you'd have to also fetch the transaction using `get_raw_transaction` and then check the input's sequences. I opened a PR rust-bitcoin/rust-bitcoin#565 to make this more convenient.

**Comment by wchance** [comment]
@sgeisler thanks for creating the new function.   Its clear to me now.
