### ISSUE TITLE
Add get_block_verbose method

### ISSUE THREAD

**Issue by morr0ne** [rust-bitcoin/rust-bitcoincore-rpc#178]
![ver](https://user-images.githubusercontent.com/35099273/118257982-965ebe00-b4af-11eb-82bd-be4aea81f02a.png)
Currently only 0 and 1 are supported.

**Comment by sgeisler** [comment]
I don't think that's really useful because we decode the block anyway and then you can just access all the transaction data that way. We don't need core to do that for us and the send us a giant JSON blob that takes time to serialize and deserialize.

I'm actually curious why we have the `fn get_block_info(&self, hash: &BlockHash) -> Result<GetBlockResult>` function. The only thing I could imagine is that one of the time fields is the time of receiving the block, which is obviously not included in the block itself? Is there any other interesting data that you only get through this API?

**Comment by morr0ne** [comment]
Using verbosity level 2 includes information about each transaction. Otherwise I'd have to make another call for each transaction hash making the process exponentially slower. We are talking about a significant difference especially when parsing the whole blockchain. The total time gets reduced from months to hours.

**Comment by morr0ne** [comment]
What I resorted to do right know is implementing a custom GetBlockResult and call the function manually:
```rust
fn into_json<T>(val: T) -> Result<serde_json::Value>
where
    T: serde::ser::Serialize,
{
    Ok(serde_json::to_value(val)?)
}

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GetBlockResult {
// fields of this new response
}

fn main() -> Result<()> {
let client = Client::new("http://127.0.0.1:8332".to_string(), Auth::None)?;
let block: GetBlockResult = client.call("getblock", &[into_json(hash)?, 2.into()])?;

Ok(())
}
```

This is of course less than ideal, it would be great if this was actually integrated in the library. I shouldn't to hard has the only field changing is tx.
[Here](https://mega.nz/folder/tfJHTITK#CsjeevO-CnHWe0akPbnl5A) are 2 json files with level 1 and 2 verbosity respectively

**Comment by RCasatta** [comment]
You may consider parsing the blocks*.dat files directly with https://github.com/RCasatta/blocks_iterator

**Comment by morr0ne** [comment]
> You may consider parsing the blocks*.dat files directly with https://github.com/RCasatta/blocks_iterator

I did try that initially but there were to many edge cases to handle while the rpc does everything in a predictable way

**Comment by sgeisler** [comment]
> Using verbosity level 2 includes information about each transaction. Otherwise I'd have to make another call for each transaction hash making the process exponentially slower. We are talking about a significant difference especially when parsing the whole blockchain. The total time gets reduced from months to hours.

I think we are still talking past each other, what I meant is: if you call [`fn get_block(&self, hash: &BlockHash) -> Result<Block>`](https://docs.rs/bitcoincore-rpc/0.13.0/bitcoincore_rpc/trait.RpcApi.html#method.get_block) you get a [`bitcoin::blockdata::block::Block`](https://docs.rs/bitcoin/0.26.0/bitcoin/blockdata/block/struct.Block.html), which contains [all transactions](https://docs.rs/bitcoin/0.26.0/bitcoin/blockdata/block/struct.Block.html#structfield.txdata) parsed out of the raw hex returned if you use verbosity level 0. There is no need to make calls per transaction even with existing functionality. 

> This is easily observable in the output size. Calling getblock with verbosity level 1 outputs a 16kb json file while verbosity level 2 outputs a file that's between 5-8 mb

* `bitcoin-cli getblock 00000000000000000008ce0cd429e76d6737c4e8f9461bedb0ab09566a236318 0` returns 2.1MB in hex, which is about 1MB of binary data representing the whole block including all transactions
* `bitcoin-cli getblock 00000000000000000008ce0cd429e76d6737c4e8f9461bedb0ab09566a236318 1` (the default when using `bitcoin-cli`) returns 23kB of JSON, not containing transactions but only their hashes
* `bitcoin-cli getblock 00000000000000000008ce0cd429e76d6737c4e8f9461bedb0ab09566a236318 2` returns 7.2MB of JSON including all the deserialized transactions

You see that verbosity 2 contains the same data as verbosity 0 but at a higher bandwidth and (de-)serialization cost. If `get_block`, which uses verbosity 0, is slower than parsing the JSON from verbosity 2 we are probably doing something horribly wrong. 

So unless the JSON contains something that is not already in the block itself I don't see a reason to use the higher verbosity. That functionality seems mostly useful in cases where your software does not easily understand the binary block format.

**Comment by morr0ne** [comment]
calling get_block doesn't include the next block hash, it includes just the previous unless there is another way to get it?

**Comment by sgeisler** [comment]
Right, that sounds like a problem. I still think if bitcoin core runs in the same network that latency will be small enough¹ that first calling `getblockhash` to get the hash and then calling `getblock <hash> 0` is still faster than `getblock <hash> 2` and the associated decoding, but I'd be happy to see a benchmark of this. If the latter is actually faster, I'd say it would be a welcome addition to the library. If not, an iterator that essentially does an optimized version of `getblockhash+getblock` would be interesting to implement (see ¹).

¹ even if that's not the case batch-requesting block hashes or running requests in parallel so that the processing pipeline stays saturated could work quite well, but we don't really support that yet out of the box/it's more complicated to build.

**Comment by 0xB10C** [comment]
> So unless the JSON contains something that is not already in the block itself I don't see a reason to use the higher verbosity. That functionality seems mostly useful in cases where your software does not easily understand the binary block format.

In on current `master` and in Bitcoin Core v22 verbosity level 2 will include the transaction fee (added in https://github.com/bitcoin/bitcoin/pull/18772) which would be extremely useful have. If https://github.com/bitcoin/bitcoin/pull/21245 is merged, verbosity level 3 adds information about the previous outputs of each transactions.

I think giving users the option to access the different verbosity levels is useful at the expense of more code here and more bandwidth used when using the verbose requests.

I'm currently using [this](https://github.com/0xB10C/rust-bitcoincore-rpc/commit/3f86c018c9f62852b48dc49a5b1a742ad7ae86ad) as a hack for [0xb10c/miningpool-observer](https://github.com/0xb10c/miningpool-observer) to call verbosity level 2 on a `master` node and plan to submit a proper `getblock` verbosity=2 patch here once Core v22 is release.

**Comment by morr0ne** [comment]
There is still reason to include verbosity level 2. Maybe we need that exact that or want to integrate into another software. I believe a rpc wrapper should be able to handle all cases regardless of how useful they are. Adding verbosity level 2 shouldn't be to hard, I'll be willing to implement it my self the maintainers are okay with it.
