### ISSUE TITLE
What this library is capable of and what is missing

### ISSUE THREAD

**Issue by morr0ne** [rust-bitcoin/rust-bitcoincore-rpc#182]
This library is great but it's missing quite a bit of functionality and it's hard to track down what's implemented and what not.

I decided to compile a list of all available and missing features.
<details>
  <summary>Blockchain RPCs</summary>
  
- [x] [getbestblockhash](https://developer.bitcoin.org/reference/rpc/getbestblockhash.html)
- [ ] [getblock](https://developer.bitcoin.org/reference/rpc/getblock.html)
    - [x] verbosity level 0
    - [x] verbosity level 1
    - [ ] verbosity level 2
- [x] [getblockchaininfo](https://developer.bitcoin.org/reference/rpc/getblockchaininfo.html)
- [x] [getblockcount](https://developer.bitcoin.org/reference/rpc/getblockcount.html)
- [x] [getblockfilter](https://developer.bitcoin.org/reference/rpc/getblockfilter.html)
- [x] [getblockhash](https://developer.bitcoin.org/reference/rpc/getblockhash.html)
- [x] [getblockheader](https://developer.bitcoin.org/reference/rpc/getblockheader.html)
- [ ] [getblockstats](https://developer.bitcoin.org/reference/rpc/getblockstats.html)
- [ ] [getchaintips](https://developer.bitcoin.org/reference/rpc/getchaintips.html)  
- [ ] [getchaintxstats](https://developer.bitcoin.org/reference/rpc/getchaintxstats.html)
- [x] [getdifficulty](https://developer.bitcoin.org/reference/rpc/getdifficulty.html)
- [ ] [getmempoolancestors](https://developer.bitcoin.org/reference/rpc/getmempoolancestors.html)
- [ ] [getmempooldescendants](https://developer.bitcoin.org/reference/rpc/getmempooldescendants.html)
- [x] [getmempoolentry](https://developer.bitcoin.org/reference/rpc/getmempoolentry.html)
- [ ] [getmempoolinfo](https://developer.bitcoin.org/reference/rpc/getmempoolinfo.html)
- [ ] [getrawmempool](https://developer.bitcoin.org/reference/rpc/getrawmempool.html)
    - [x] verbose false
    - [ ] verbose true
- [x] [gettxout](https://developer.bitcoin.org/reference/rpc/gettxout.html)
- [x] [gettxoutproof](https://developer.bitcoin.org/reference/rpc/gettxoutproof.html)
- [x] [gettxoutsetinfo](https://developer.bitcoin.org/reference/rpc/gettxoutsetinfo.html)
- [ ] [preciousblock](https://developer.bitcoin.org/reference/rpc/preciousblock.html)
- [ ] [pruneblockchain](https://developer.bitcoin.org/reference/rpc/pruneblockchain.html)
- [ ] [savemempool](https://developer.bitcoin.org/reference/rpc/savemempool.html)
- [x] [scantxoutset](https://developer.bitcoin.org/reference/rpc/scantxoutset.html) 
- [ ] [verifychain](https://developer.bitcoin.org/reference/rpc/verifychain.html)
- [ ] [verifytxoutproof](https://developer.bitcoin.org/reference/rpc/verifytxoutproof.html)
</details>

<details>
  <summary>Control RPCs</summary>

- [ ] [getmemoryinfo](https://developer.bitcoin.org/reference/rpc/getmemoryinfo.html)
- [ ] [getrpcinfo](https://developer.bitcoin.org/reference/rpc/getrpcinfo.html)
- [ ] [help](https://developer.bitcoin.org/reference/rpc/help.html)
- [ ] [logging](https://developer.bitcoin.org/reference/rpc/logging.html)
- [x] [stop](https://developer.bitcoin.org/reference/rpc/stop.html)
- [x] [uptime](https://developer.bitcoin.org/reference/rpc/uptime.html) 
</details>

<details>
  <summary>Generating RPCs</summary>

- [ ] [generateblock](https://developer.bitcoin.org/reference/rpc/generateblock.html)
- [x] [generatetoaddress](https://developer.bitcoin.org/reference/rpc/generatetoaddress.html)
- [ ] [generatetodescriptor](https://developer.bitcoin.org/reference/rpc/generatetodescriptor.html)
</details>

<details>
  <summary>Mining RPCs</summary>

- [ ] [getblocktemplate](https://developer.bitcoin.org/reference/rpc/getblocktemplate.html)
- [x] [getmininginfo](https://developer.bitcoin.org/reference/rpc/getmininginfo.html)
- [x] [getnetworkhashps](https://developer.bitcoin.org/reference/rpc/getnetworkhashps.html)
- [ ] [prioritisetransaction](https://developer.bitcoin.org/reference/rpc/prioritisetransaction.html)
- [ ] [submitblock](https://developer.bitcoin.org/reference/rpc/submitblock.html)
- [ ] [submitheader](https://developer.bitcoin.org/reference/rpc/submitheader.html)
</details>

<details>
  <summary>Network RPCs</summary>

soon
</details>

<details>
  <summary>Rawtransactions RPCs</summary>

soon
</details>

<details>
  <summary>Util RPCs</summary>

soon
</details>

<details>
  <summary>Wallet RPCs</summary>

soon
</details>

The list is not complete yet because it take a bit of time to write everything down. Nonetheless I'm sharing what I've done so far. 
I feel something like this is essential to build a roadmap and actually get an understanding of the progress of the library

**Comment by sgeisler** [comment]
> Nonetheless I'm sharing what I've done so far. I feel something like this is essential to build a roadmap and actually get an understanding of the progress of the library

I can't speak for everyone, but at least my impression is that stuff just gets implemented whenever someone actually needs it and there is no real "roadmap" :laughing: but we are always happy about PRs.

**Comment by morr0ne** [comment]
I got the same impression :laughing:
I think having a clear list of what is possible with this library will help a bit

**Comment by 0xB10C** [comment]
fwiw: getchaintips support was added in https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/164

**Comment by 0xB10C** [comment]
and getblocktemplate in https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/163 but this still needs https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/176
