### ISSUE TITLE
`HexBytes` are not very convenient 

### ISSUE THREAD

**Issue by dongcarl** [rust-bitcoin/rust-bitcoincore-rpc#19]
See: https://github.com/rust-bitcoin/rust-bitcoin/issues/200

**Comment by stevenroose** [comment]
@dpc I remember the API changed since you had this issue. Is it still a problem?

**Comment by stevenroose** [comment]
I think specifically for the methods you mention, we introduced a `_hex` that takes `HexBytes` and a regular variant that takes the rust-bitcoin type like `Transaction`. So I think this should no longer be a problem.

**Comment by dpc** [comment]
I'm not sure. Probably OK to close. :)
