### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoincore-rpc#194]
There is a [RUSTSEC advisory](https://rustsec.org/advisories/RUSTSEC-2021-0078.html) for `hyper`. `rust-bitcoincore-rpc` depends on a recent version of `hyper` that is not effected by the advisory. However there has been no release since the update to `hyper` was merged [1].

Can we have a v0.14 release please so downstream users of this library can avoid the security advisory.

Thanks,
Tobin.

[1] commit: `54a427f Merge pull request #180 from Start9Labs/dependencies/jsonrpc`

**Comment by Tibo-lg** [comment]
Would be great to have #188 as well for a new release.
