### ISSUE TITLE
How to get value to put in &[GetBlockTemplateCapabilities] as an argument for get_block_template()?

### ISSUE THREAD

**Issue by matthiasdebernardini** [rust-bitcoin/rust-bitcoincore-rpc#219]
I am trying to get the block template of my core node so I can implement this in rust.

https://code.samourai.io/oxt/one_dollar_fee_estimator/-/blob/master/one_dollar_fee_estimator/estimator.py

Below is my code that wont compile and I can't figure out how to use the rpc call correctly just from looking at the docs.

How would I supply the get block template call with the correct capabilities? Looks like I need to get a value from the enum to put in the array but I can't figure out how to invoke one from the docs.

This is the function signature that I copied from the docs.
fn [get_block_template](https://docs.rs/bitcoincore-rpc/0.14.0/bitcoincore_rpc/trait.RpcApi.html#method.get_block_template)(
    &self, 
    mode: [GetBlockTemplateModes](https://docs.rs/bitcoincore-rpc-json/0.14.0/x86_64-unknown-linux-gnu/bitcoincore_rpc_json/enum.GetBlockTemplateModes.html), 
    rules: [&[](https://doc.rust-lang.org/nightly/std/primitive.slice.html)[GetBlockTemplateRules](https://docs.rs/bitcoincore-rpc-json/0.14.0/x86_64-unknown-linux-gnu/bitcoincore_rpc_json/enum.GetBlockTemplateRules.html)[]](https://doc.rust-lang.org/nightly/std/primitive.slice.html), 
    capabilities: [&[](https://doc.rust-lang.org/nightly/std/primitive.slice.html)[GetBlockTemplateCapabilities](https://docs.rs/bitcoincore-rpc-json/0.14.0/x86_64-unknown-linux-gnu/bitcoincore_rpc_json/enum.GetBlockTemplateCapabilities.html)[]](https://doc.rust-lang.org/nightly/std/primitive.slice.html)
) -> [Result](https://docs.rs/bitcoincore-rpc/0.14.0/bitcoincore_rpc/type.Result.html)<[GetBlockTemplateResult](https://docs.rs/bitcoincore-rpc-json/0.14.0/x86_64-unknown-linux-gnu/bitcoincore_rpc_json/struct.GetBlockTemplateResult.html)>

This is my code that I am trying to get running.

```rust
use std::error::Error;
use bitcoincore_rpc::RpcApi;
fn main() -> Result<(), Box<dyn Error>> {
    let client = bitcoincore_rpc::Client::new("http://127.0.0.1:38333",bitcoincore_rpc::Auth::UserPass("".to_string(), "".to_string()))?;
    let mode = bitcoincore_rpc::json::GetBlockTemplateModes::Template;
    let rules = &[bitcoincore_rpc::json::GetBlockTemplateRules::Signet, bitcoincore_rpc::json::GetBlockTemplateRules::Taproot, bitcoincore_rpc::json::GetBlockTemplateRules::SegWit, bitcoincore_rpc::json::GetBlockTemplateRules::Csv];
    let capabilities = bitcoincore_rpc::json::GetBlockTemplateCapabilities;
    let rpc = client.get_block_template(mode, rules, capabilities);
    Ok(())
}
```

I also tried lookind up this example but I think its no longer valid (or at least it wont compile for me.

https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/163#issue-807338109

this is my cargo.toml for reference

```toml
[package]
name = "one-dollar-estimator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statistical = "1.0.0"
ringbuf = "0.2.8"
bitcoincore-rpc = "0.14.0"
bitcoincore-rpc-json = "0.14.0"
```

Appreciate any pointers, not sure what I am doing wrong here.

**Comment by 0xB10C** [comment]
Have a look at e.g.

https://github.com/0xB10C/miningpool-observer/blob/e8eb52dea2c15527c9784fd431b03ac951a44647/daemon/src/main.rs#L233-L239

but I think the result you get form that RPC call to a v0.21 or newer node is currently broken. See https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/176. I'm running a patched version of this crate as the fix hasn't been merged yet.

**Comment by matthiasdebernardini** [comment]
@0xB10C thank you very much, I was able to get it running.

I'll share it here for good measure.

If it belongs elsewhere, let me know.

```rust
use bitcoincore_rpc::RpcApi;
use bitcoincore_rpc::json::GetBlockTemplateRules::{SegWit, Signet, Taproot, Csv};
use bitcoincore_rpc;

fn main() {
    let client = bitcoincore_rpc::Client::new("http://127.0.0.1:38332", bitcoincore_rpc::Auth::UserPass("hello".to_string(), "there".to_string()))?;
    let mode = bitcoincore_rpc::json::GetBlockTemplateModes::Template;
    let rules = &[Signet, SegWit, Taproot, Csv];
    let capabilities = &[];
    let rpc = client.get_block_template(mode, rules, capabilities)?;
}
```

**Comment by 0xB10C** [comment]
Awesome! Feel free to close this issues if it's solved.
