### ISSUE TITLE
IPv6 support – use jsonrpc 0.13.0

### ISSUE THREAD

**Issue by schildbach** [rust-bitcoin/rust-bitcoincore-rpc#256]
For some reason, even though the current version of bitcoincore-rpc has been released after jsonrpc 0.13.0, it still depends on 0.12.0 in the Cargo repository. The old version doesn't support IPv6, leading to errors like in this issue: https://github.com/romanz/electrs/issues/792

I assume a fix would be easy, just update the version of jsonrpc to 0.13.0 and (optionally) add a unit test for URLs with IPv6 addresses.

**Comment by Kixunil** [comment]
0.13 is in master, so in effect this is a duplicate of #253

**Comment by schildbach** [comment]
You're right, I'm closing this. Thanks!

**Comment by Whiskey992** [comment]
Yeah
