### ISSUE TITLE
`gettxout` may use incorrect scriptPubKey struct

### ISSUE THREAD

**Issue by thesimplekid** [rust-bitcoin/rust-bitcoincore-rpc#260]
`gettxout` uses the `GetRawTransactionResultVoutScriptPubKey` struct which has the field `pub addresses: Option<Vec<Address>>` which does line up with the [developer.bitcoin.org docs](https://developer.bitcoin.org/reference/rpc/gettxout.html), However when I run with core v23.0.0 (I know not officially supported by this crate) the correct field seems to be `pub address: Option<Address>` (screenshot below). Not sure if this is a change to the RPC api 
![Screenshot from 2022-11-29 20-28-50](https://user-images.githubusercontent.com/8606367/204685260-bc5c7d20-7116-49c4-a27f-85dc8d159f78.png)

**Comment by apoelstra** [comment]
It is a change to the RPC API, yep, which I guess happened between Core 22 and 23. Frustrating.

**Comment by thesimplekid** [comment]
Same issues as #214 so ill close this
