### ISSUE TITLE
Add importdescriptors

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoincore-rpc#264]
I noticed that there's a PR for this #248 but not an issue. I wanted to open an issue because I happened to need this, and it was quite hard to get right.

**Comment by apoelstra** [comment]
Are you able to test #248 ?

**Comment by casey** [comment]
Added to my backlog! I'll give it a whirl soon.

**Comment by casey** [comment]
Just tested, seems to work! Imported descriptors are visible in Bitcoin Core.

**Comment by casey** [comment]
Closing, since #248 has been merged.
