### ISSUE TITLE
get_blockchain_info() errors because SoftforkType is missing bip8

### ISSUE THREAD

**Issue by benma** [rust-bitcoin/rust-bitcoincore-rpc#267]
Hi

I have an error on `client.get_blockchain_info()`:

```
`Err` value: Json(Error("unknown variant `bip8`, expected `buried` or `bip9`", line: 0, column: 0))'
```

When running this against litecoind v0.21.2.1.

The problem seems to be here:

https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/master/json/src/lib.rs#L878-L881

Could this variant be added, or an "Unknown" variant that catches unexpected output?

**Comment by apoelstra** [comment]
Yeah, we should add an "Unknown" variant, otherwise we'll have crashes every time a new fork is defined.

**Comment by benma** [comment]
> Yeah, we should add an "Unknown" variant, otherwise we'll have crashes every time a new fork is defined.

Maybe not - looks like the whole softforks section was removed as of 24.0.1:

https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.0.1.md#updated-rpcs

Would still be nice to add it for the above reason, or to remove it altogether.

**Comment by apoelstra** [comment]
Ah, interesting. I still think we should add an unknown variant, even though this section is never going to be used again.

I suspect that it's not only litecoin, but old versions of Core, that are currently broken.

**Comment by benma** [comment]
How to proceed? Will you do a PR, should I? Would be great to get a release out with the fix asap so our stuff works again after I upgraded our Litecoin node.

**Comment by benma** [comment]
> If you could do a PR, I'm happy to ack and merge it. To get a release out we need @stevenroose. See #253.

Done here: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/268
