### ISSUE TITLE
How to connect a third party provider?

### ISSUE THREAD

**Issue by oneforalone** [rust-bitcoin/rust-bitcoincore-rpc#277]
I'm using quicknode as my node provider, after trying with: 

```rust
use bitcoincore_rpc::{Auth, Client, Error, RpcApi};

fn main() {
    let https_url = "quicknode_provider_url";
    let client = Client::new(https_url, Auth::None).unwrap();
    let version = client.version().unwrap();
    println!("{}", version);
}
```
And got an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(HttpParseError))'
```

And after reading the source codes, looks like there's no way to connect to a third party's node? Am i missing something?

**Comment by apoelstra** [comment]
Your issue is probably that this library's underlying HTTP transport does not support HTTPS. In practice this probably means that you can't connect to any non-local nodes unless you add a local proxy or something.

We have some plans to switch our HTTP implementation to `minreq` but there's a fair bit of prepatory work we need to do (and we'll need some cooperation from the authors of that library, probably), but until we get that sorted, this is the situation.

**Comment by oneforalone** [comment]
Okay, I see. I just made it with `hyper` crate, but it seems that there's lots method should write from the scratch. 

And what comes in my mind is, just change the HTTP implementation in `jsonrpc` crate, cause I've noticed that you are using `jsonrpc` crate for HTTP connection. However, I'm kind new with Rust and Bitcoin, just can't tell which is better. Writing it from scratch using `hyper` / `minreq`, or modifying this repos codes? Could you give me some advice?

**Comment by apoelstra** [comment]
@oneforalone if you want to switch to Hyper I'd advise to start from scratch -- it's actually not too complicated. You just make HTTP requests then parse the resulting data using `serde_json::from_reader` or something like that.

What this crate gives you are pre-defined data structures for the responses that Bitcoin Core gives to RPC calls, but if you only need a couple RPCs, these are easy to implement yourself.

**Comment by oneforalone** [comment]
> What this crate gives you are pre-defined data structures for the responses that Bitcoin Core gives to RPC calls, but if you only need a couple RPCs, these are easy to implement yourself.

Got it, really appreciate.
