### ISSUE TITLE
Various output descriptor RPC functions not implemented

### ISSUE THREAD

**Issue by wild-kard** [rust-bitcoin/rust-bitcoincore-rpc#280]
I have noticed various RPC functions which support output descriptors missing from the Client implementation
`importdescriptors`
`generatedescriptor`
`utxoupdatepsbt`
`createmultisig`
`listdescriptors`
`scanblocks`

**Comment by wild-kard** [comment]
Apologies, I missed that this was in the JSON library

**Comment by chrisguida** [comment]
Where is `scanblocks` implemented?? I'm not seeing it in the JSON library...
