### ISSUE TITLE
Transport(HttpResponseTooShort { actual: 0, needed: 12 })

### ISSUE THREAD

**Issue by Sotatek-VuNguyen2** [rust-bitcoin/rust-bitcoincore-rpc#333]
Hi I am struggling with very simple code using public node. Currently use the 0.18.0 version
```
    let rpc_url = "http://198.154.93.110:8333/";

    let client = Client::new(
        rpc_url,
        Auth::None,
    )
    .unwrap();
    let info = client.get_blockchain_info().unwrap();
    println!("info {:?}", info);
   ```
   Sadly I search but couldn't find the solution for this, tried to use different version but it keep getting different errors

**Comment by RCasatta** [comment]
Hi, what do you mean by public node?

Rpc port should not be exposed publicly

**Comment by Sotatek-VuNguyen2** [comment]
@RCasatta I got from this link https://bitnodes.io/nodes/leaderboard/. I tried some others 3rd party like quicknode, etc but seem like it use `https` which is cause the error response 400. Then my only option is to run my own node ? that kinda hard for my mid range computer

**Comment by RCasatta** [comment]
You are connecting to the P2P port (8333 by default) while the rpc port is 8332 by default. But you can't access RPC on public nodes you need your own

Once synced bitcoind with pruning enabled doesn't require much resources

**Comment by Sotatek-VuNguyen2** [comment]
Thanks, then I'll try to use my own node

**Comment by Sotatek-MinhNguyen11** [comment]
@RCasatta  i follow this link: https://github.com/ruanbekker/bitcoin-full-node-demo/blob/main/guides/setup_bitcoin_core.md, but i have this issue: 
![Screenshot from 2024-04-04 17-51-37](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/assets/146687333/5205a143-2161-401f-ade6-3e02acdf93b6)

**Comment by RCasatta** [comment]
Bitcoin core repo is github.com/bitcoin/Bitcoin
Or you can download binaries from  https://bitcoincore.org/en/download/

Closing because we are off topic now
