### ISSUE TITLE
Found single-character string literal pattern

### ISSUE THREAD

**Issue by philipjonsen** [rust-bitcoin/rust-bitcoincore-rpc#335]
DESCRIPTION:

Certain str functions, such as .split() and .find() work on patterns that accept both string literals as well as characters. When using such functions, prefer chars over single-character string literals as they are more performant.

Replace the single-character string literal with a char.

BAD PRACTICE
let x = "hello, world";
x.find("o"); // single-character str

RECOMMENDED
let x = "hello, world";
x.find('o'); // use a char instead

rust-bitcoincore-rpc/blob/master/client/src/client.rs#L212-L212

**Comment by mubarak23** [comment]
@TheBlueMatt am submitting a PR for this
