### ISSUE TITLE
Switch to taking `&self`?

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoincore-rpc#4]
Since https://docs.rs/jsonrpc/0.10.2/jsonrpc/client/struct.Client.html is taking everything by `&self`, and libraries underneath will take care of `Sync`, there's no point in introducing friction in this layer, and forcing people to wrap `Client` in `Mutex`, etc.

**Comment by dpc** [comment]
PR #5

**Comment by stevenroose** [comment]
Done
