### ISSUE TITLE
`Auth` is not very convenient

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoincore-rpc#42]
`<'a>` is meh, especially if one doesn't want to use it all.

I started updating to rust-bicoin 0.18, so I'll probably create more issues like this. Excuse my terseness.

**Comment by dpc** [comment]
No `impl Clone for Auth` it seems.

**Comment by dpc** [comment]
`#[derive(Clone, Debug, Hash, Eq, PartialEq, Ord, PartialOrd)]`

**Comment by stevenroose** [comment]
Considering this is how Auth looks right now, I'm gonna close this; let me know if you still think Auth is inconvenient.
```rust
#[derive(Clone, Debug, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum Auth {
    None,
    UserPass(String, String),
    CookieFile(PathBuf),
}
```
