### ISSUE TITLE
Re-export types from dependencies used in public APIs

### ISSUE THREAD

**Issue by thomaseizinger** [rust-bitcoin/rust-bitcoincore-rpc#50]
The `Error` enum has variants for `JsonRpc`, `FromHexError` etc.

Especially for the `JsonRpc` one, it would be handy if the crate would re-export the type so that it is accessible for downstream crates without having to add a dependency on `jsonrpc` itself.

**Comment by stevenroose** [comment]
That's a very good point. I didn't know until a few months back that you could re-export dependent modules entirely. I should probably do that in the case of this crate.

**Comment by thomaseizinger** [comment]
I am not sure if we need to re-export the whole thing. It is a safe catch-all for this particular problem but at the same time, could cause issues regarding versioning. If you re-export everything, it will be part of your public API and hence, every breaking API change in the downstream crate would technically be a breaking change for your crate.
