### ISSUE TITLE
Remove dependence on rust-bitcoin

### ISSUE THREAD

**Issue by D4nte** [rust-bitcoin/rust-bitcoincore-rpc#81]
On several projects, we are not able to upgrade to the latest rust-bitcoin version because we use rust-bitcoincore-rpc in some automated tests and it has a later version.

I am contemplating/working on the idea of removing the dependency.
It works pretty well, replacing rust-bitcoin types with type parameters that can then be passed at the call site by the user.

There are less obvious changes such as some helper outpoint `From` implementations that I am thinking of moving to a separate sub-crate that will be the only subcrate to depend on rust-bitcoin (or provide a `FromStr`/`Display` trait implementations for `JsonOutpoint` that renders in the `Outpoint` format `txidhex:vout`):

https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/83e101434d7594267737918f50f4b1eefa444d32/client/src/client.rs#L44

What is the maintainers' take on the idea?

**Comment by vorot93** [comment]
`rust-bitcoin` is a good foundational crate and it's extremely convenient to use its types for RPC calls. We shouldn't be trying to mitigate the issue of lack of updates by dodging the type system altogether.
