### ISSUE TITLE
Donating my crate name to rust-bitcoin

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-bitcoincore-rpc#85]
Long time ago like one year or so I used to be to involved with some projects of mine related to bitcoin and even `rust-bitcoin`, and like so I tried to write a crate that did RPC stuff using rust-jsonrpc, never finished it, and now that there is an official rust-bitcoin project that does RPC with the bitcoind daemon I would like to donate the [`bitcoin-rpc`](https://crates.io/crates/bitcoin-rpc) crate name. Of course, I'll remove myself from the crate owners if you accept it.

**Comment by jeandudey** [comment]
And the [bitcoin-rpc-json](https://crates.io/crates/bitcoin-rpc-json) too

**Comment by stevenroose** [comment]
That's really generous! I think we kind of wanted to make a point by explicitly mentioning `core` in the name because "bitcoin" doesn't have an RPC principally speaking.

If you want to get rid of it, I could take the name, though. Just to make sure it's not lost in case we want to use it. Or to make sure it doesn't get into the hands of a malicious actor. Up to you.

**Comment by jeandudey** [comment]
> 
> 
> That's really generous! I think we kind of wanted to make a point by explicitly mentioning `core` in the name because "bitcoin" doesn't have an RPC principally speaking.
> 
> If you want to get rid of it, I could take the name, though. Just to make sure it's not lost in case we want to use it. Or to make sure it doesn't get into the hands of a malicious actor. Up to you.

I thought the same when I created my crate, the name it's a bit off (mine's). But there is the name, of course I'd want to make sure it doesn't get in the wrong hands. Let me know and I'll add you as a owner (or anyone else in rust-bitcoin) and then you remove me.

**Comment by jeandudey** [comment]
> 
> 
> Or of course if any of the other contributors would prefer the `bitcoin-rpc` name over our current one.

**Comment by stevenroose** [comment]
My crates.io e-mail is github@stevenroose.org (it's linked to this GitHub account).

**Comment by jeandudey** [comment]
I sent an invitation

**Comment by stevenroose** [comment]
Let's keep you in it as well, just in case. Thanks!
