### ISSUE TITLE
fees negative in rpc

### ISSUE THREAD

**Issue by JanPel** [rust-bitcoin/rust-bitcoincore-rpc#89]
In the pub struct GetTransactionResult, Amount is used for the fee. But Bitcoin core gives negative numbers back for fees. So maybe SIgnedAmount should be used? Similarly for the amount field in GetTransactionResultDetail.  
see: https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/gettransaction/

Happy to make a pull request to change it.

**Comment by stevenroose** [comment]
Hmm yeah we should use SignedAmount for that.

**Comment by stevenroose** [comment]
Fixed in 69b40f6870d0b44952509b58e6f7272956701fa1.
