### ISSUE TITLE
Review/Land pending PRs, upgrade dependency on `rust-bitcoin` and release 0.2?

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoincore-rpc#9]

**Comment by stevenroose** [comment]
I realize I've been procrastinating looking at your PRs for the last weeks. Do you have a tight deadline? I don't have much time this week and next week I'm on holidays. After that I can look at all the things, though.

**Comment by stevenroose** [comment]
I realize I've been procrastinating looking at your PRs for the last weeks. Do you have a tight deadline? I don't have much time this week and next week I'm on holidays. After that I can look at all the things, though.

My apologies!

**Comment by dpc** [comment]
No deadlines. Just pinging. This can wait couple of weeks, no worries.

**Comment by stevenroose** [comment]
Done!
